### ISSUE TITLE
Choice of MHC allele

### ISSUE THREAD

**Issue by MiqG** [KarchinLab/bigmhc#1]
Hi,

thanks for developing such a great tool.

Since there are many possible MHC I alleles, should one run the prediction of every peptide for each possible MHC allele or do you have some tricks to constrain the list of possibilities or obtain an averaged result?

I am specifically referring to the `--allele` option for predictions.

Thanks in advance,

Miquel

**Comment by benjaminalbert** [comment]
Hi Miquel,

Thank you for your interest. BigMHC currently runs on peptide-MHC pairs, so the intended use-case is that, given a patient's genotype and their mutated proteins, one would screen all patient-specific genotype/mutation pairs with BigMHC. In other words, given 6 HLA alleles and, say, N mutated peptides, then you will have 6*N rows of peptide-MHC pairs to screen.

Does this help?

**Comment by MiqG** [comment]
Yup! Perfectly. Thanks a lot!

Miquel
