### ISSUE TITLE
The Choice of BigMHC method, BA,EL or IM?

### ISSUE THREAD

**Issue by shudanhua** [KarchinLab/bigmhc#10]
Hi,

Thank you for this great tool.

I'm using pvactools for neo-epitope screening. There is Binding Affinity predictors, EL predictors (include BigMHC_EL) and Immunogenicity predictors (include BigMHC_IM) available .

I'm wondering if it is reccomended to use one of the method above? or use BigMHC_IM to rank BA predictor / EL predictor identified candidate peptide-MHC complex. 

Thanks again
Danhua

**Comment by benjaminalbert** [comment]
Hi, @shudanhua, in our study, we did not experiment with ranking BigMHC EL predictions using BigMHC IM. It makes intuitive sense, but unfortunately we do not have data to support that approach. For this reason, I would generally recommend just using BigMHC IM.

However, if your MHC of interest is found in the BigMHC EL training set but not seen in the IM training data (or only rarely seen), then you may see better results by prescreening using BigMHC EL and subsequently ranking by BigMHC IM, but again, I do not have data to support this.

**Comment by shudanhua** [comment]
Thank you so much for your prompt reply ;). That answers my question well.
