### ISSUE TITLE
USE SHAP TO EXPLAIN MODEL

### ISSUE THREAD

**Issue by wunaiwuhuang** [KarchinLab/bigmhc#13]
dear author:
i really like your tool, its precision and efficiency is definitly top around existing tools. recently i m trying to use SHAP https://github.com/shap/shap to test your model, but get tons of trouble. if its possible ,would you mind offering me a simple code (just using your example1.csv as example)which can successfully run? thank you very much

**Comment by benjaminalbert** [comment]
Hi @wunaiwuhuang, please see the README for instructions and examples on usage, and please let me know if it answers your question!

**Comment by wunaiwuhuang** [comment]
i am sorry, i ve read your readme and almost all your source code. i noticed your model requires two variables mhc and pep. but shap seems to only accept one. so if it is possible to package two vars into one and deliver it to shap

**Comment by benjaminalbert** [comment]
While I don't know SHAP, you could write a very tiny child class of BigMHC to process the forward inputs differently. For example, if you wrote a class that inherits from BigMHC, you could write the forward method to take a tuple and pass the elements of that tuple to the super class forward method as mhc and pep args.

**Comment by wunaiwuhuang** [comment]
thanks, i will explore more. in addition ,could you offer me your attention matrix(MHC binding part)? i m doing a benchmark work now and found your tool performe greater than other tools. through your article doi:10.1038/s42256-023-00694-6. i only find part.(Extended Data Fig. 1)，if you can offer me your attention matrix i can compare it with other tools and describe your tool's shine points better.

**Comment by benjaminalbert** [comment]
To get those matrices used in the extended figs, you can generate them using this notebook: https://github.com/KarchinLab/bigmhc/blob/master/nb/attention.ipynb

To run this notebook, you will first need to download `datasets.zip` and `eltrainval_models.zip` from the data repository: https://doi.org/10.17632/dvmz6pkzvb.4 and extract the contents to the data directory within the bigmhc dir.

The notebook will attempt to load a file called `el_trainval.csv`, which you can make by concatenating `el_train.csv` and `el_val.csv`.

After preparing the data, you can run the notebook and the third cell should cache the attention matrices as pickled objects located at `cache/el_mean_att_train.pkl` and `cache/el_mean_att_test.pkl`.

If you run into difficulties with this, please let me know!

**Comment by wunaiwuhuang** [comment]
its good. but i d like to get such kind of matrix https://doi.org/10.1038/s42256-022-00459-7 Fig. 5 | Attention scores . do you have any idea?

**Comment by wunaiwuhuang** [comment]
his code is https://github.com/a96123155/TransPHLA-AOMP/blob/master/Procedure%20Code/pHLAIformer-%E6%9C%80%E7%BB%88%E6%A8%A1%E5%9E%8B-%E6%B3%A8%E6%84%8F%E5%8A%9B%E5%A4%84%E7%90%86-%E5%90%88%E5%B9%B6%E7%9C%8B%E6%80%BB%E7%9A%84%E5%85%B3%E9%94%AE%E4%BD%8D%E7%82%B9.ipynb
i don't know if you have relevent files which can generate similar results

**Comment by benjaminalbert** [comment]
BigMHC can produce attention values for each of the pseudosequence residues, but it does not attend to the peptide residues, so it is not possible to generate those graphs seen in TransPHLA fig 5.

Are you interested in generating those graphs for the pseudosequences?

**Comment by wunaiwuhuang** [comment]
thank you for your explanation, i ve found an alternative to solve my problem. i am now very interested in your framework, cause i am classifing those tools now. could you define your tool in simple words? e.g. Attention-based Convolutional neural networks//transformer or so. i haven't read your defination in your paper

**Comment by benjaminalbert** [comment]
BigMHC uses self-attention + LSTM.

I'll go ahead and close this thread, but feel free to start a new one if you have further issues!
