### ISSUE TITLE
about output results

### ISSUE THREAD

**Issue by Xiaoguang-Shi** [KarchinLab/bigmhc#3]
Hello, thank you for providing this tool. I have some confusion regarding the interpretation of the output results. How can I understand the affinity and immunogenicity from the BigMHC_EL and BigMHC_IM results? Is there a reasonable cutoff value?

**Comment by benjaminalbert** [comment]
Hi @Xiaoguang-Shi ,

The scores that BigMHC produces are in the range (0,1) but it is primarily intended to sort a list of putative neoepitopes. For example, if one has the capacity to validate N neoepitopes per patient in vitro, then one would rank all neoepitopes (potentially stratifying by allele first) and take the top N to validate. From those N that are validated, a subset that generated an in vitro immune response may be usable in an immunotherapy. From this pipeline, the "cutoff" is dictated solely by the capacity for experimental validation.

If for some reason you still want to approximate an output threshold, you could estimate that number based on ROC and/or PR curves for a metric of interest (e.g. choose the threshold that preserves approximately X precision).

**Comment by Xiaoguang-Shi** [comment]
Thank you for your reply.I will try according to your suggestion.

**Comment by benjaminalbert** [comment]
Hi @Xiaoguang-Shi, I wanted to follow up and see if this is still an issue?

**Comment by zhangkn3** [comment]
Hi Benjamin,
Thanks for the development of the software.
I found the BigMHC IM range from 0 to 1. Will the neoantigen candidate be more immunogenetic when the value of BigMHC IM is higher or lower?

**Comment by benjaminalbert** [comment]
Hi @zhangkn3, higher output indicates greater immunogenicity.

**Comment by zhangkn3** [comment]
Thanks for your quick response!
