### ISSUE TITLE
Questions about input files and results

### ISSUE THREAD

**Issue by fenghua0811** [KarchinLab/bigmhc#5]
Hello, thank you for providing this tool.I have two questions about this tool, what does 'tgt' mean in the input file 'example1.csv'? Is there a recommended threshold for scoring to judge the binding？

**Comment by benjaminalbert** [comment]
Hi @fenghua0811, tgt is the target score.

Please let me know if this answers your second question: https://github.com/KarchinLab/bigmhc/issues/3#issuecomment-1634753826

**Comment by fenghua0811** [comment]
Thanks for your reply, I will consider the method you mentioned in another answer. Of course, I would prefer to have a clear threshold to help me judge.

**Comment by benjaminalbert** [comment]
While I understand that you wish to binarize the outputs, that is not the intended use of BigMHC; instead, its outputs should be used to rank/prioritize pMHCs. Authors of other immunogenicity predictors (e.g. PRIME) have described similar usage.
