### ISSUE TITLE
bits files in makeseqs

### ISSUE THREAD

**Issue by Cmfffff** [KarchinLab/bigmhc#9]
hello there:
    wonderful work for predicting affinity of peptide and mhc,
    I am trying to generate pseudo sequences following the [jupyter](https://github.com/KarchinLab/bigmhc/blob/master/nb/makeseqs.ipynb), in the instruction I do not see how bits file was generating? it would be much appreciated if you can provide any suggestions!
    thank you !

**Comment by benjaminalbert** [comment]
Hi, @cmf1997, I apologize for the delay. We have added step-by-step instructions for generating pseudosequences to the [makeseqs.ipynb notebook](https://github.com/KarchinLab/bigmhc/blob/master/nb/makeseqs.ipynb). Please let me know if this answers your question!

**Comment by Cmfffff** [comment]
thanks for you reply!
I have tried the make logo function in sam tool,
but It only return a eps file
`./makelogo mhc -i mhc.mod &> mhc.bits`
I assumed this code would return a bits file, but actually did not, 
also, I generate bits from eps file, but it's such a dummy solution, this there anything I missed?

**Comment by benjaminalbert** [comment]
Did you build from the source provided? The source has been modified to print out the entropy. I will make a note of this in the notebook to clarify.

**Comment by Cmfffff** [comment]
that must be something I miss,
I check the README, there is a Installation step
`./sam-t-configure `which perl`, I will run it again!
it would be much easier to reproduce if you can clarify.
thanks a lot!

**Comment by benjaminalbert** [comment]
The SAM README is potentially outdated. Although we provided all the SAM source code along with its original instructions, following the instructions specifically in the `makeseqs.ipynb` notebook are all you should need. Let me know if that resolves things for you!

**Comment by Cmfffff** [comment]
thanks for your explicitly reply! I would check for it once available
